/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnilib_TestJNI */

#ifndef _Included_jnilib_TestJNI
#define _Included_jnilib_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnilib_TestJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnilib_TestJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
